name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      
      - name: Setup dev db
        run: npm run test:setup:db
      
      - name: Run unit test 
        run: npm run test:ci

  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
      
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies  
        run: npm ci

      - name: Run unit test 
        run: npm run lint

  audit:
    name: Run audit
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
      
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies  
        run: npm ci

      - name: Run audit 
        run: npm audit